# Generated by Django 2.2 on 2019-04-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.TextField(max_length=400)),
                ('lastchecked', models.DateField()),
                ('sql_i_score', models.BooleanField()),
                ('xss_score', models.BooleanField()),
            ],
            options={
                'ordering': ['lastchecked'],
            },
        ),
    ]
